### ISSUE TITLE
Restore to path should actually do what it says

### ISSUE THREAD

**Issue by jagaimoworks** [garethgeorge/backrest#333]
Currently the restoring to path option creates an additional "restic-restore-xyz" directory under the specified path. As mentioned in #118 this is done to prevent potentially unwanted destruction of data. This however is not reflected by the UI leading the user to expect backrest to restore into the specified path which, in my eyes, would be the desired behavior anyway.

Not restoring a backup in place requires a full additional copy before its data can be moved to where its supposed to be. Requiring double the space on big backups is not exactly great.

Not wanting to disregard the original intent with the current behavior I suggest a simple "is the provided path empty"-check combined with a warning dialog and maybe have a "safe" path as a default.

If non of this seems acceptable for now I suggest putting the generated directory name behind the "Restore to path" text input to make it visually consistent at least.

**Comment by garethgeorge** [comment]
I agree that backrest unexpectedly modifying the restore path is odd behavior and it's something I'll go ahead and cleanup in the release with a few changes

 * Better defaults populated in the UI when opening the restore dialogue
 * The path is accepted on the backend w/o modification, if no path is provided Downloads folder is used

I'm open to restore in place now that Backrest is 1.0.0 but I think this is probably a new capability that needs some feature work and significant attention re: validation and test coverage. It's not high priority at the moment for me but I'll leave this open to track.

**Comment by garethgeorge** [comment]
Restore to path now respects the specified path, resolved in the last few versions

**Comment by Corvalan** [comment]
> Restore to path now respects the specified path, resolved in the last few versions

Hi @garethgeorge—thanks for fixing the subdirectory issue so that “Restore to path” now uses the specified path directly. However, I still don’t see a way for Backrest to overwrite files in that path if they already exist. Can we enable a true “overwrite everything” restore without first clearing or renaming the target folder?

I know newer Restic versions have --overwrite flags (always, if-newer, etc.), but I don’t see those exposed in Backrest. Is full in-place overwriting supported or planned? If not, what’s the recommended approach to revert a volume in one step?
